apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  labels:
    app: auth-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec: 
      containers: 
      - name: auth-api
        image: docker.etisoftware.com/auth-api:latest
        envFrom:
        - configMapRef:
            name: api-config-map
        ports:
        - containerPort: 8080
        command: ["java"]
        args: ["-Djava.security.egd=file:/dev/./urandom","-XX:-TieredCompilation","-jar","/app.jar"]
      imagePullSecrets:
      - name: regcred