apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  labels:
    app: auth-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec: 
      containers: 
      - name: auth-api
        image: docker.etisoftware.com/auth-api:latest
        envFrom:
        - configMapRef:
            name: api-config-map
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: triad-config
          mountPath: /usr/cbridge/config/
      volumes:
        - name: triad-config
          configMap: 
            name: auth-api-config

      imagePullSecrets:
      - name: regcred