apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  labels:
    app: auth-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec: 
      containers: 
      - name: auth-api
        image: docker.etisoftware.com/auth-api:1.0.0
        envFrom:
        - configMapRef:
            name: api-config-map
        ports:
        - containerPort: 8080

      imagePullSecrets:
      - name: regcred