apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-api-deployment
  labels:
    app: location-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: location-api
  template:
    metadata:
      labels:
        app: location-api
    spec: 
      containers: 
      - name: location-api
        image: docker.etisoftware.com/location-api:1.1.1
        envFrom:
        - configMapRef:
            name: api-config-map
        ports:
        - containerPort: 8080

      imagePullSecrets:
      - name: regcred