apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-map
data:
  # Where the database is
  TRIAD_DB_HOST: "137.116.52.213"
  # The host of the APIs that is used to generate HATEOS
  API_HOST: "oss.d-data.orchestrationengine.com"
  LOG_LEVEL: "DEBUG"
  # Override the logging stuff in the application.properties
  # file so that Spring will write logs to STDOUT
  LOGGING_FILE_PATH: ""
  LOGGING_FILE_MAX-SIZE: ""
  LOGGING_FILE_MAX-HISTORY: ""
